#!/bin/bash
#
# install_bcm43xx_firmware without network
#
# This script installs the firmware needed to run WLAN cards
# using Broadcom's bcm43xx chips without needing the network.

# firmware for b43
FILE1=broadcom-wl-5.100.138.tar.bz2
FIRMWARE1=broadcom-wl-5.100.138/linux/wl_apsta.o

# firmware for b43legacy
FILE2=wl_apsta-3.130.20.0.o

test -d /lib/firmware || mkdir -p /lib/firmware

TMPDIR=$(mktemp -d /var/tmp/bcm.XXXXXX) || exit 1

cp $FILE1 $TMPDIR/.

pushd $TMPDIR >/dev/null

echo "Extracting b43 firmware"
tar xjf $FILE1
b43-fwcutter -w /lib/firmware $FIRMWARE1

echo
if [ -d /lib/firmware/b43 ] ; then
	echo "b43 firmware successfully installed."
else
	echo "b43 firmware installation failed."
fi
popd >/dev/null
rm -rf $TMPDIR

echo
echo "Extracting b43legacy firmware"
b43-fwcutter -w /lib/firmware $FILE2

if [ -d /lib/firmware/b43legacy ] ; then
	echo "b43legacy firmware successfully installed."
else
	echo "b43legacy firmware installation failed."
fi

echo "You may want to reboot now to allow the driver to access the new firmware"

